# Generated by Django 5.1.4 on 2024-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
