# Generated by Django 5.1.4 on 2024-12-20 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentfees_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField(default=datetime.date(1990, 1, 1))),
                ('signup_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
